name: Run ruff and mypy

runs:
  using: composite
  steps:
    - name: Flake8 code
      shell: bash -el {0}
      run: |
        ruff format --check .
        ruff check .

    - name: Mypy check
      if: always()
      shell: bash -el {0}
      run: python3 -m mypy .
