name: Bug report
description: Create a report if you believe something is not working
title: "[BUG]: "
labels: ["bug"]

body:
  - type: textarea
    id: description
    attributes:
      label: How to reproduce the bug
      description: Tell us how one can reproduce the bug
      placeholder: Run `python3 -m pytest -xvs test`
    validations:
      required: true
  - type: textarea
    id: output
    attributes:
      label: Error output
      description: If you get an error message or any output, please add it here
      render: bash
      placeholder: |
        root@1516b1da338c:~/shared# python3 -m pytest -xvs test/
        ============================================= test session starts ==============================================
        platform linux -- Python 3.10.4, pytest-7.1.3, pluggy-1.0.0 -- /usr/bin/python3
        cachedir: .pytest_cache
        rootdir: /root/shared
        plugins: anyio-3.6.1, cov-3.0.0
        collected 1 item                                                                                               

        test/test_code.py::test_addition PASSED
        ============================================== 1 passed in 0.01s ===============================================
    validations:
      required: false
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 0.1.0
        - main branch
    validations:
      required: true
  - type: textarea
    id: system
    attributes:
      label: system
      description: What operating system are you using?
      placeholder: i.e. "I'm Ubuntu 20.04" or "Im using Windows 11"
  - type: textarea
    id: extra
    attributes: 
      label: Additional information
      description: If you have any additional information, please add it here.
      placeholder: You can drag and drop files here to attach them
