name: Publish documentation

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["release"]
  pull_request:
    branches: ["release"]
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-docs:
    uses: ./.github/workflows/docs.yml
    with:
      tag: "stable"

  run-tests:
    uses: ./.github/workflows/tests.yml
    with:
      tag: "stable"

  deploy:
    if: github.event_name == 'push'
    runs-on: ubuntu-22.04
    needs: [build-docs, run-tests]
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Download docs artifact
        uses: actions/download-artifact@v5
        with:
          name: documentation
          path: "./documentation"

      - name: Download docs artifact
        uses: actions/download-artifact@v5
        with:
          name: code-coverage-report
          path: "./documentation/code-coverage-report"

      - name: Upload page artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "./documentation"

      - name: Deploy coverage report to GH Pages
        id: deployment
        uses: actions/deploy-pages@v4
