name: Build documentation

on:
  pull_request:
    branches:
      - main

  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag of DOLFINx docker image'
        default: 'nightly'
        required: true
        type: string
  workflow_call:
    inputs:
      tag:
        description: 'Tag of DOLFINx docker image'
        default: 'nightly'
        required: true
        type: string

env:
  DEB_PYTHON_INSTALL_LAYOUT: deb_system

jobs:
  build:
    runs-on: ubuntu-22.04
    env: 
      DEFAULT_TAG: nightly
      DEB_PYTHON_INSTALL_LAYOUT: deb_system    
    container: ghcr.io/fenics/dolfinx/dolfinx:${{ inputs.tag || github.env.DEFAULT_TAG }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: python3 -m pip install ".[test,docs]"

      - name: Build docs
        run: jupyter book build -W docs/

      - name: Upload documentation
        uses: actions/upload-artifact@v4
        with:
          name: documentation
          path: ./docs/_build/html
          if-no-files-found: error
