name: Check formatting

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - main

env:
  DEB_PYTHON_INSTALL_LAYOUT: deb_system

jobs:
  check-code:
    runs-on: ubuntu-22.04
    container: ghcr.io/fenics/dolfinx/dolfinx:nightly

    steps:
      - uses: actions/checkout@v4

      - name: Install code
        run: python3 -m pip install .[test]

      - name: Flake8 code
        run: python3 -m flake8 .

      - name: Mypy check
        run: python3 -m mypy .
