name: Test package against stable release

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

env:
  DEB_PYTHON_INSTALL_LAYOUT: deb_system

jobs:
  tests:
    runs-on: ubuntu-22.04
    container: ghcr.io/fenics/dolfinx/dolfinx:stable

    steps:
      - name: Checkout at last working position
        uses: actions/checkout@v4
        with:
          ref: v1.0.0
          # ${{ github.ref }} # once backward compatibility is broken this should be pinned to a release

      - name: Install oasisx
        run: python3 -m pip install .[test,docs]

      - name: Run tests
        run: python3 -m pytest

      - name: Run demos
        run: |
          python3 demo/taylor_green.py  -N 8 -N 16 -N 32 -dt=0.005
          python3 demo/assembly_strategies.py
